name: .NET Build and Test

on: 
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test Analyzer
      run: dotnet test --no-restore --verbosity normal ./test/Moxposer.Analyzer.Tests/Moxposer.Analyzer.Tests.csproj

    - name: Test Runner
      run: dotnet test --no-restore --verbosity normal ./test/Moxposer.Runner.Tests/Moxposer.Runner.Tests.csproj
